---
apiVersion: v1
kind: Namespace
metadata:
  name: sdm
---
apiVersion: v1
kind: Secret
metadata:
  name: sdm-secret
  namespace: sdm
data:
  SDM_SERVICE_TOKEN: N/A
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sdm
  name: deployment-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - image: 232288579625.dkr.ecr.eu-west-1.amazonaws.com/full-api:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
      - image: quay.io/sdmrepo/client
        imagePullPolicy: Always
        name: sdm
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: SDM_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: sdm-secret
              key: SDM_SERVICE_TOKEN
        ports:
        - containerPort: 13306
---
apiVersion: v1
kind: Service
metadata:
  namespace: sdm
  name: service-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30278
  type: NodePort
  selector:
    app.kubernetes.io/name: api

